on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

name: test mac build

jobs:
  build:
    name: Cargo Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy 
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
